# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
#  1/4a6fc49a88361847209c851b0b40552c51aab97f
version: 2
jobs:
  build_webwallet:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm run apply:decred
      - run: node_modules/.bin/cordova telemetry off
      - run: npm run final:www
      - run: cp -r www dist

      - setup_remote_docker

      - run: docker build -f Dockerfiles/Dockerfile-production -t decred/webwallet .
      - run: docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
      - run: docker tag decred/webwallet:latest registry.heroku.com/dcrwallet/web
      - run: docker push registry.heroku.com/dcrwallet/web

  build_android-app:
    docker:
      - image: bitriseio/docker-android

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm run apply:decred
      - run: node_modules/.bin/cordova telemetry off
      - run: npm run final:www
      - run: cp -r www dist

      - run: npm run build:android

      - store_artifacts:
          path: /bitrise/src/repo/platforms/android/build/outputs/apk

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build_webwallet:
          filters:
            tags:
              only: /^STAGING_.*/
